version: "3.8"
services:
  app:
    container_name: lastfm-elt
    build: 
      context: ./ 
      dockerfile: ./Dockerfile
    #command: lambda_function.handler
    ports:
      - 9000:8080 
    volumes:
      - .:/var/task
    environment:
      - ENV=dev   
volumes:
  app:
    driver: local
