version: "3.8"
services:
  app:
    container_name: lastfm-elt
    build: 
      context: ./ 
      dockerfile: ./Dockerfile
    #command: lambda_function.handler
    ports:
      # - 9000:8080 original
      - 9090:9090
    volumes:
      - .:/var/task
    environment:
      - ENV=dev   

  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      # - <host_directory>:<container_directory>:<access_mode>
      # - ./trino/etc:/etc/trino
      - ./lastfm-warehouse:/lastfm-warehouse
    networks:
      - trino-network

  postgres:
    container_name: postgres-db
    image: postgres:14.1-alpine
    #restart: always
    environment:
      - POSTGRES_DB=postgres_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trino-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
    - 9000:9000 # CLI
    - 9001:9001 # Web 
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      #- /path/to/data:/data
      - ./lastfm-warehouse:/lastfm-warehouse
    command: server /lastfm-warehouse

  minio-client:
    image: minio/mc
    # insure that the server container is running before building the client
    depends_on:
      - minio


volumes:
  app:
    driver: local

networks:
  trino-network:
    driver: bridge
