lastfm:
  outputs:
  
    prd:
      database: awsdatacatalog
      region_name: us-east-1
      s3_data_dir: s3://lastfm-warehouse/dbt/s3_data_dir/
      s3_staging_dir: s3://lastfm-warehouse/dbt/s3_staging_dir/
      schema: lastfm
      threads: 1
      type: athena
      
    dev:
      type: trino
      user: trino
      password: 
      host: trino
      database: iceberg
      schema: lastfm
      port: 8080
      threads: 1
      
  target: dev
  